### ISSUE TITLE
Server upgrade script installed automatically

### ISSUE THREAD

**Issue by accidentaldeveloper** [gbowerman/azure-minecraft#2]
Using the server upgrade script I just completed an upgrade of my Azure minecraft server to the newest version. It was straightforward and relatively easy, even for a Linux noob like myself. Thank you!! 
However, I think it could be easier. Would it be possible to place the server upgrade script on the VM when it is initially created? Then upgrading the server would take just a couple lines of code.
If you like this idea I'm happy to contribute but I may need some direction.

**Comment by accidentaldeveloper** [comment]
It would also be nice if passing "latest" (or similar) to the script would install the latest version of minecraft server. I don't know if Mojang exposes this information in a form that's easy to query but it would be nice to have.

**Comment by gbowerman** [comment]
Hi @accidentaldeveloper sorry I missed this.. both of these are good ideas. I'm nearly 2 years too late responding, but I'm happy to work on this. Also, on the off-chance that you're still around, if you want to work on this please do.

**Comment by accidentaldeveloper** [comment]
Thanks for the response! My plate is a bit full right now but I'll let you know if time opens up to work on this.

**Comment by gbowerman** [comment]
Fair enough, thanks. Here's what I'm planning to work on over the next few weeks:
- Upgrade template to Ubuntu 18.04-LTS.
- Fix upgrade script (roll in latest fixes from main deployment script).
- Include upgrade script in deployment (i.e. this issue).
- Design a container based solution which deploys faster and more reliably (as it will skip the Java and Minecraft download and install steps).

**Comment by gbowerman** [comment]
Update on this issue. This issue has been fixed, with first 3 items on the above to-do list complete (OS upgrade, fix upgrade script, deploy upgrade script to server). The _mcupgrade.sh_ script available here: [minecraft-server-ubuntu](https://github.com/gbowerman/azure-minecraft/tree/master/azure-marketplace/minecraft-server-ubuntu) and here: [scripts](https://github.com/gbowerman/azure-minecraft/tree/master/scripts) perform an upgrade. 

You can download them directly for your existing Minecraft installations (make sure you also download mcdownload.py which requires Python 3), or wait for the new version of the Marketplace solution to be published - it's submitted for review so should published this week.

Thanks for logging this issue (which I took way too long to address). Closing as fixed.

**Comment by accidentaldeveloper** [comment]
Thank you!
