### ISSUE TITLE
Server install script fails due to Java download requiring license

### ISSUE THREAD

**Issue by MIchaelMainer** [gbowerman/azure-minecraft#3]
First off, thank you for providing this template. I'm using the template from the marketplace to install a MineCraft server. The deployment never completes as it gets stuck in a loop trying to download Java. That's because of of this: https://stackoverflow.com/questions/10268583/downloading-java-jdk-on-linux-via-wget-is-shown-license-page-instead

Anyways, I thought I'd open this in case other people were encountering this. My BashFoo isn't strong so I may or may not get to making a PR on this.

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27628  100 27628    0     0    98k      0 --:--:-- --:--:-- --:--:--   98k
Reading package lists... Done
Building dependency tree       
Reading state information... Done
software-properties-common is already the newest version (0.96.20.7).
0 upgraded, 0 newly installed, 0 to remove and 25 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up oracle-java8-installer (8u151-1~webupd8~0) ...
Using wget settings from /var/cache/oracle-jdk8-installer/wgetrc
Downloading Oracle Java 8...
--2018-01-21 06:25:06--  http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz
Resolving download.oracle.com (download.oracle.com)... 104.91.214.56
Connecting to download.oracle.com (download.oracle.com)|104.91.214.56|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://edelivery.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz [following]
--2018-01-21 06:25:06--  https://edelivery.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz
Resolving edelivery.oracle.com (edelivery.oracle.com)... 104.109.198.7, 2600:1409:a:39c::2d3e, 2600:1409:a:39e::2d3e
Connecting to edelivery.oracle.com (edelivery.oracle.com)|104.109.198.7|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz?AuthParam=1516516026_aa5488484acbe6015691aff7bafa9e2f [following]
--2018-01-21 06:25:06--  http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz?AuthParam=1516516026_aa5488484acbe6015691aff7bafa9e2f
Connecting to download.oracle.com (download.oracle.com)|104.91.214.56|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-01-21 06:25:06 ERROR 404: Not Found.

download failed
Oracle JDK 8 is NOT installed.
dpkg: error processing package oracle-java8-installer (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 oracle-java8-installer
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by MIchaelMainer** [comment]
Just in case it is useful to anyone else, here are the steps I've taken towards getting MineCraft installed using the [install_minecraft.sh](https://github.com/gbowerman/azure-minecraft/blob/master/azure-marketplace/minecraft-server-ubuntu/install_minecraft.sh).

1) Connected to the Ubuntu VM via the Connect instructions in the Azure portal.
2) Got the download URL by accepting the license from the download page.
3) Followed these instructions to setup Java 
https://www.tecmint.com/install-java-jdk-jre-in-linux/
4) Made a Gist of install_minecraft.sh and commented out the part for getting Java.
5) Added my configuration to the script variables $1 through $9. I'm doing this all wrong. Ignorign for now.
6) chmod 0755 on my script
7) ran the script, there's many things wrong.
8) sudo mkdir minecraft-server since that dir didn't exist. Ran it again. 

I'm now getting a bad substitution at rawUUID=${mojang_output:7:32}. Will try this more later.

**Comment by pwilliamson** [comment]
Hi MIchaelMainer, I am having the same issue. Did you ever manage to get Minecraft successfully installed?

**Comment by MIchaelMainer** [comment]
Hi @pwilliamson . No, I never got back to this. And then I got lazy and bought a Realms subscription. I probably won't get back to this until my kids' modding demands reach a fever pitch.

**Comment by pwilliamson** [comment]
OK, pity, thanks for the response

**Comment by mirekszym** [comment]
seems it's still not working. all the resources are created on the azure side, VM is reachable, but minecraft server is not installed. it ends up with "deployment status unknown" in the azure portal and "unit minecraft-server.service not found" when logging into VM.

**Comment by gbowerman** [comment]
Hi guys, very sorry I didn't notice there were issues open until now. The Azure Marketplace Minecraft template is currently working fine in my tests. I realize you've probably moved on to other things by now, but if anyone gets the chance, please give it a try. Thanks!

**Comment by gbowerman** [comment]
After a few more test deployments this appears to be fixed. Closing for now. Note: For a future release I want to shift this into containers as a pre-installed package to avoid problems like Java installation errors.

**Comment by MIchaelMainer** [comment]
Thank you for the follow up @gbowerman. I actually tried to deploy over a month ago and was unsuccessful. From activity log:

![image](https://user-images.githubusercontent.com/8527305/47869795-18d97380-ddc5-11e8-8412-60d48d258df8.png)

JSON

```
{
    "authorization": {
        "action": "Microsoft.Resources/deployments/write",
        "scope": "/subscriptions/11216475-170e-469a-8245-17926ddee472/resourceGroups/Minecraft/providers/Microsoft.Resources/deployments/Microsoft.Template"
    },
    "caller": "thedude@example.com",
    "channels": "Operation",
    "claims": {deletedByTheDude},
    "correlationId": "0cce93d0-5b90-4be7-98a0-c42ae7b9d697",
    "description": "",
    "eventDataId": "96d3a002-2f1f-4c8f-b6b5-3050bca72bbf",
    "eventName": {
        "value": "EndRequest",
        "localizedValue": "End request"
    },
    "category": {
        "value": "Administrative",
        "localizedValue": "Administrative"
    },
    "eventTimestamp": "2018-09-28T00:04:57.3474935Z",
    "id": "/subscriptions/11216475-170e-469a-8245-17926ddee472/resourceGroups/Minecraft/providers/Microsoft.Resources/deployments/Microsoft.Template/events/96d3a002-2f1f-4c8f-b6b5-3050bca72bbf/ticks/636736898973474935",
    "level": "Error",
    "operationId": "43138591-cb78-42f7-ab95-e2aab5d1d39b",
    "operationName": {
        "value": "Microsoft.Resources/deployments/write",
        "localizedValue": "Create Deployment"
    },
    "resourceGroupName": "Minecraft",
    "resourceProviderName": {
        "value": "Microsoft.Resources",
        "localizedValue": "Microsoft Resources"
    },
    "resourceType": {
        "value": "Microsoft.Resources/deployments",
        "localizedValue": "Microsoft.Resources/deployments"
    },
    "resourceId": "/subscriptions/11216475-170e-469a-8245-17926ddee472/resourceGroups/Minecraft/providers/Microsoft.Resources/deployments/Microsoft.Template",
    "status": {
        "value": "Failed",
        "localizedValue": "Failed"
    },
    "subStatus": {
        "value": "",
        "localizedValue": ""
    },
    "submissionTimestamp": "2018-09-28T00:05:12.0825609Z",
    "subscriptionId": "11216475-170e-469a-8245-17926ddee472",
    "properties": {
        "statusCode": "OK",
        "serviceRequestId": null
    },
    "relatedEvents": []
}
```

If I recall correctly, there was a script that never completed and I think something timed out. I think I also needed to change the target plan since the plan identifiers have changed. I might need to try this out tonight and capture the entire repro step by step, image by image and post it here.
