### ISSUE TITLE
Forge Requires Oracle JDK

### ISSUE THREAD

**Issue by matthewfcarlson** [gbowerman/azure-minecraft#4]
First off, thanks for making it super easy to spin up an azure server!

This is similar but slightly different from #3. The switch to OpenJDK works great for vanilla server but the Forge/Spigot versions absolutely require oracle. Maybe I'm just a noob, but a quick link to some helpful articles would have saved me some time. Just a simple tip to what's wrong could help the next person to try what I did :)

This article was helpful:
https://www.itzgeek.com/how-tos/linux/ubuntu-how-tos/install-java-jdk-8-on-ubuntu-14-10-linux-mint-17-1.html

Happy to submit a PR updating the readme with some additional information!

**Comment by gbowerman** [comment]
Hey @matthewfcarlson  sorry for missing this. I'm just getting back to maintaining this repo after updates were blocking in Azure Marketplace for a while. 

Thanks a lot for pointing this out. Yes, please do submit a PR for the readme. Whatever you write I'll quote you in a blog post too.

Guy

**Comment by matthewfcarlson** [comment]
Hey sorry it took me a while to get back to you. I'll get on this!

**Comment by gbowerman** [comment]
Hey @matthewfcarlson  I added a note to the readme based on your issue comment. If you want to change or enhance it please do send a PR. Thanks again for calling this out.

**Comment by matthewfcarlson** [comment]
Yeah I'm really sorry, this has been on my inbox for months. I'll took a look at your commit and it looks great. Thanks for the very much undeserved shout out :)
